---
- name: create backend directory
  become: yes
  file:
    path: root/backend
    state: directory
    mode: 0755

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy artifact
  become: yes
  copy:
    src: project/artifact.tar.gz
    dest: root/backend/artifact.tar.gz

- name: Unpack Artifact
  become: yes
  shell: |
    cd root/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: Start App
  become: yes
  shell: |
    cd root/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env



