---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend and unzip
  template:
    src: "backend/artifact.tar.gz"
    dest: "~/web"

- name: Start App
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
