---
- name: Creates directory
  become: true
  file:
    path: ~/backend
    state: directory

- name: Copy backend and unzip
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: unpack backend files
  become: true
  shell: |
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
  args:
    chdir: ~/backend

- name: Start App
  become: true
  shell: |
    npm install
    pm2 start npm -- run start
  args:
    chdir: ~/backend



