---
- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start App 1
  become: true
  shell: |
    apt-get install tar gzip

- name: Start App 2
  become: true
  shell: tar -xf artifact.tar.gz

- name: Start App 3
  become: true
  shell: rm -f artifact.tar.gz

- name: Start App 4
  become: true
  shell: npm install

- name: Start App 5
  become: true
  shell: pm2 stop default

- name: Start App 6
  become: true
  shell: pm2 start npm -- start

