---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Start App
  become: true
  shell: cd root/web

- name: Start App 2
  become: true
  shell: apt-get install tar gzip

- name: Start App 3
  become: true
  shell: tar -xf artifact.tar.gz

- name: Start App 3
  become: true
  shell: cd backend

- name: Start App 4
  become: true
  shell: npm install

- name: Start App 5
  become: true
  shell: pm2 stop default

- name: Start App 6
  become: true
  shell: pm2 start npm -- start

