---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/web

- name: Start App
  shell: |
    apt-get install tar gzip
    tar -xf artifact.tar.gz
    rm -f artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
