---
- name: Copy backend and unzip
  copy:
    src: /root/project/artifact.tar.gz
    dest: /root/backend

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: unpack backend files
  become: yes
  shell: |
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
  args:
    chdir: /root/backend

- name: Start App
  become: true
  shell: |
    npm install
    pm2 start npm -- run start
  ergs:
    chdir: /root/backend



