---
- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/
  
- name: Pwd
  raw: pwd

- name: Start App 1
  become: true
  shell: |
    apt-get install tar gzip
    apt-get install nodejs
    apt-get install npm
    apt-get install pm2

- name: Start App 2
  become: true
  shell: tar -xf artifact.tar.gz

- name: Start App 3
  become: true
  shell: rm -f artifact.tar.gz

- name: Start App 4
  become: true
  shell: npm install

- name: Start App 5
  become: true
  shell: pm2 stop default

- name: Start App 6
  become: true
  shell: pm2 start npm -- start

