---
- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Start App 1
  become: true
  shell: |
    apt-get install tar gzip
    tar -xf artifact.tar.gz
    rm -f artifact.tar.gz
    npm install
    pm2 start npm -- run start


