---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend and unzip
  copy:
    src: "~/backend.tar.gz"
    dest: "~/web"

- name: Start App
  shell: |
    apt-get install tar gzip
    tar -xf archive.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
