---
- name: Copy backend and unzip
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/
  
- name: Pwd
  raw: pwd

- name: Start App
  become: true
  shell: |
    apt-get install tar gzip
    tar -xf artifact.tar.gz
    rm -f artifact.tar.gz
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
